databases:
  - name: postgres
    databaseName: rag_documents
    user: rag_user
    plan: free

services:
  # Redis service
  - type: redis
    name: redis
    plan: free
    maxmemoryPolicy: allkeys-lru

  # Backend service
  - type: web
    name: backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: GEMINI_API_KEY
        value: AIzaSyCyjfH5GrYf0gaCv0Hb_KIYR6nPEAWrDCs
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000

  # Frontend service
  - type: web
    name: frontend
    runtime: docker
    dockerfilePath: ./Dockerfile.frontend
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: backend
          property: host
