// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdycmxwshedaafqghhna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkeWNteHdzaGVkYWFmcWdoaG5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MTIwNTAsImV4cCI6MjA3MTA4ODA1MH0.7uRbeLQL8KxPXrA4gvzufubqAyuu5WMttZb3JO4Re9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});