// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js'

// Define the database schema types
export interface Database {
  public: {
    Tables: {
      documents: {
        Row: {
          id: string
          name: string
          size: number
          content: string
          chunks: string[]
          status: 'processing' | 'processed' | 'error'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          size: number
          content: string
          chunks: string[]
          status?: 'processing' | 'processed' | 'error'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          size?: number
          content?: string
          chunks?: string[]
          status?: 'processing' | 'processed' | 'error'
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}

export const supabase = createClient<Database>(
  import.meta.env.VITE_SUPABASE_URL,
  import.meta.env.VITE_SUPABASE_ANON_KEY
)